# Generated by Django 5.1.4 on 2024-12-28 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tabla_PreferenciaMusical',
            new_name='Tabla_FavoritosUsuario',
        ),
        migrations.DeleteModel(
            name='Cancion',
        ),
    ]
