# Generated by Django 5.1.4 on 2024-12-30 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyAPI', '0003_remove_tabla_usuario_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabla_favoritos_usuario',
            name='top_5_recomendaciones',
            field=models.JSONField(default=list),
        ),
    ]
