# Generated by Django 5.1.4 on 2024-12-30 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotifyAPI', '0004_alter_tabla_favoritos_usuario_top_5_recomendaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabla_favoritos_usuario',
            name='top_5_recomendaciones',
        ),
        migrations.AddField(
            model_name='tabla_favoritos_usuario',
            name='album_cancion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tabla_favoritos_usuario',
            name='generos_artista',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='tabla_favoritos_usuario',
            name='popularidad_cancion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tabla_favoritos_usuario',
            name='seguidores_artista',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
